### ISSUE TITLE
Sorting does not work correctly with negative numbers

### ISSUE THREAD

**Issue by Zauras** [TanStack/react-table#3450]
Sorting does not work with negative numbers

I have data [ -1, -5, 0, 8, 1]

Expected: [-5, -1, 0, 1, 8]
Actual: [0, -1, 1, 5, 8]

Tried in columns:
   accessor: (data) => Number(data.percentageDiff)
   sortType: 'number'
   sortMethod: (a, b) => Number(a) - Number(b)

Version: react-table: ^7.7.0

**Comment by Zauras** [comment]
Seems my issue was solved by column property:         
* sortType: 'basic'

But in general sorting is buggy I have poor documentation

**Comment by onemorekiril** [comment]
Yes, I've noticed the same issue when using the "number" sorting type. And I agree with the author that using the "basic" type solves the issue. It's strange because you don't expect such behavior when using sorting by number.

**Comment by YuCJ** [comment]
https://github.com/tannerlinsley/react-table/blob/8c77b4ad97353a0b1f0746be5b919868862a9dcc/src/sortTypes.js#L103-L112

I think we can remove the redundant `.replace(replaceNonNumeric, '')` in `'number'` sortType. It will cause the comparing with negative numbers buggy. Besides, when using `'number'` sortType,  we can expect that the user has already prepared the right format of number values to be compared.

**Comment by mcookdev** [comment]
This is still an issue, will there be a resolution for the current version?

**Comment by tannerlinsley** [comment]
v8 has a better story around this with the `basic` sortType and the removal of the `number` sortType. For now in v7, we're going to stick with the approach of using `basic`.
